### PR TITLE
Vlan support

### PR DESCRIPTION
**Pull request by artem-sidorenko**
Implemented VLAN support

### CODE REVIEW

**Comment by artem-sidorenko** [comment]
@slashbeast ping

**Comment by slashbeast** [comment]
So I finally found motivation to pick it up.

I've merged your changes with a bit of rework in functions.sh and additional bringing down the physif. Can you please check on it and let me know whatever it works for you now?

**Comment by slashbeast** [comment]
errr, the vconfig is actually a dynamically linked binary.

**Comment by slashbeast** [comment]
Changed in another commit to make it static. Now I really need you to test it.

**Comment by artem-sidorenko** [comment]
looks good, works for me
Thx for merging!

**Pull request merged**
