### PR TITLE
Added support for SquashFS with AuFS mounted TmpFS.

### PR DESCRIPTION
**Pull request by schmidmt**
I've added support for mounting a SquashFS as root with a tmpfs for storing temporary changes to root.

### CODE REVIEW

**Comment by schmidmt** [comment]
Closing old stuff

**Comment by slashbeast** [comment]
Sorry about that. At some point I still plan to add squashfs + overlayfs since it's now mainline. Tho my number one priority is to switch now to Alpine Linux as build root, and a new build system that sucks less that what's now.

**Comment by slashbeast** [comment]
I do not think so I will put effort into this project in any near future, if at all. I no longer use it on daily basis and most likely will archive it at some point.

**Comment by DrMcCoy** [comment]
What are you using instead, if I may ask?

**Comment by slashbeast** [comment]
A Dracut on Fedora and my main workstation is running MacOS so this does not apply to it.

**Pull request closed without merging**
